### ISSUE TITLE
Respect Environnent Variables

### ISSUE THREAD

**Issue by jaywilliams** [neutralinsomniac/obsdpkgup#1]
I don't know if you are looking to handle other possible use cases, but `pkg_add(1)` supports a number of [environment variables](https://man.openbsd.org/pkg_add.1#ENVIRONMENT), two of which are relevant to your program `PKG_PATH` & `TRUSTED_PKG_PATH`.

Also, as of [OpenBSD 6.6](https://www.openbsd.org/plus66.html), `syspatch(8)` defaults to `cdn.openbsd.org` if an installurl isn't defined. I don't know if that would be useful to add or not, but I figured it was worth mentioning.

**Comment by neutralinsomniac** [comment]
I will get on this. Thanks for the report!

**Comment by neutralinsomniac** [comment]
I believe this https://github.com/neutralinsomniac/obsdpkgup/commit/21abb17cdf68c4ee230781d36e2ac9ae28d4266e covers everything you mentioned here. What do you think?

**Comment by neutralinsomniac** [comment]
Calling this one fixed. Please create a new issue if you find problems with the current implementation :)
